<?php

namespace BackendBundle\Repository;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapituloRepository extends \Doctrine\ORM\EntityRepository
{
}
