<?php

namespace BackendBundle\Repository;

/**
 * NumeroSueniosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiaRepository extends \Doctrine\ORM\EntityRepository
{
}
